defaults:
- _self_
- datasets

data_dir: data

model:
  name: resnet18
  
dataset:
  name: tinyimagenet

checkpoint: resnet18_cifar10

# sane
transformer:
  n_blocks: 2 # original was 8
  blocksize: 288 # idim & wsize
  n_head: 2 # original was 16
  edim: 256 # original was 2048
  dropout: 0.0
  bias: False
  causal: False

training:
  n_classes: 10
  stride: 4 # stands for window_size
  batch_size: 32
  device: cuda
  num_workers: 4 
  loss_reduction: "mean"
  n_epochs: 1000
  patience: 10

test:
  test_error: False
  reconstruction_error: True

augmentation:
  noise_std: 0.01
  layers_to_noise: ['layer4', 'fc']
  n_checkpoints: 3

optimizer:
  lr: 1e-4
  wd: 3e-9
  scheduler: "OneCycleLR"

experiment:
  mode: "augmented" # "base" or "augmented"
  zoo: True
  noise_percentage: 0.02

log:
  dir: "./logs"
  wandb: True
  tensorboard: False

wandb:
  entity: krys12-universit-di-pisa
  project: sane-base
  dir: logs/wandb